spring:
  application:
    name: springMallServer
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8080
server:
  port: ${port:8080}
  compression:
    enabled: true